version: "3.7"

networks:
  head-watcher: {}

services:

  app-mainnet:
    container_name: ethereum-head-watcher-mainnet
    build: .
    restart: unless-stopped
    networks:
      - head-watcher
    deploy:
      resources:
        limits:
          memory: 2g
    depends_on:
      - prometheus
      - alertmanager
      - alertmanager-discord
    expose:
      - 9000
    environment:
      - CONSENSUS_CLIENT_URI=${CONSENSUS_CLIENT_URI}
      - KEYS_API_URI=${KEYS_API_URI}
      - ALERTMANAGER_URI=${ALERTMANAGER_URI}
      - LOG_LEVEL=${LOG_LEVEL}

  app-goerli:
    container_name: ethereum-head-watcher-goerli
    build: .
    restart: unless-stopped
    networks:
      - head-watcher
    deploy:
      resources:
        limits:
          memory: 2g
    depends_on:
      - prometheus
      - alertmanager
      - alertmanager-discord
    expose:
      - 9000
    environment:
      - CONSENSUS_CLIENT_URI=${CONSENSUS_CLIENT_URI_GOERLI}
      - KEYS_API_URI=${KEYS_API_URI_GOERLI}
      - ALERTMANAGER_URI=${ALERTMANAGER_URI}
      - LOG_LEVEL=${LOG_LEVEL}
      - NETWORK_NAME=goerli

  prometheus:
    image: prom/prometheus:latest
    sysctls:
      - net.ipv6.conf.lo.disable_ipv6=0
      - net.ipv6.conf.all.disable_ipv6=0
    container_name: prometheus
    networks:
      - head-watcher
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256m
    volumes:
      - ./.volumes/prometheus/:/prometheus
      - ./docker/prometheus/:/etc/prometheus/
    expose:
      - 9090

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    restart: unless-stopped
    networks:
      - head-watcher
    deploy:
      resources:
        limits:
          memory: 64m
    volumes:
      - ./.volumes/alertmanager/:/alertmanager
      - ./docker/alertmanager/:/etc/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    expose:
      - 9093

  alertmanager-discord:
    image: lidofinance/alertmanager-discord:2.3.0
    platform: linux/x86_64
    container_name: alertmanager-discord
    restart: unless-stopped
    networks:
      - head-watcher
    expose:
      - 5001
    volumes:
      - ./docker/alertmanager-discord/alertmanager-discord.yml:/etc/alertmanager-discord.yml