version: "3.7"
services:
  ethereum-slashing-watcher:
    build: .
    container_name: ethereum-slashing-watcher
    deploy:
      resources:
        limits:
          memory: 2g
    restart: unless-stopped
    environment:
      - CONSENSUS_CLIENT_URI=${CONSENSUS_CLIENT_URI}
      - KEYS_API_URI=${KEYS_API_URI}
