global:
  scrape_interval: 5s
  evaluation_interval: 5s
  external_labels:
    monitor: 'my-project'

alerting:
  alertmanagers:
    - static_configs:
      - targets: ['alertmanager:9093']

rule_files:
  - "alerts_rules.yml"

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'app'
    static_configs:
      - targets: ['ethereum-slashing-watcher:9000']
